services:
  # run jupyter notebook inside jupyter 
  jupyter-notebook:
    image:  chikire/airline_ticket_prediction:d4ab7c7
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
