name: airline_ticket_prediction
channels:
- conda-forge
dependencies:
- python=3.9.23
- pandas=2.3.1
- altair=5.5.0
- numpy=1.26.4
- pip=25.2
- jupyterlab
- click=8.1.8
- make=4.4.1
- pytest=8.4.1
- pyarrow=21.0.0
- scikit-learn=1.6.1
- scipy=1.13.1
- ipykernel=6.30.1
- tabulate=0.9.0
- setuptools=80.9.0
