name: airline_ticket_prediction
channels:
- conda-forge
dependencies:
- python=3.9
- pandas=2.3
- altair=5.5
- numpy=1.26
- pip=25
- jupyterlab
- click=8.1
- make=4.4
- pytest=8.4
- pyarrow=21
- scikit-learn=1.6
- scipy=1.13
- ipykernel=6.30
- tabulate=0.9
- setuptools=80
